/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AssociateId = IDL.Nat;
export const AssociateApplicationId = IDL.Nat;
export const InquiryId = IDL.Nat;
export const PartnerId = IDL.Nat;
export const PartnerLeadId = IDL.Nat;
export const InquiryStatus = IDL.Variant({
  'new' : IDL.Null,
  'closed' : IDL.Null,
  'reviewed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const AssociateApplication = IDL.Record({
  'id' : AssociateApplicationId,
  'cvBlobKey' : IDL.Text,
  'status' : InquiryStatus,
  'yearsOfExperience' : IDL.Text,
  'fullName' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'techStackOrRole' : IDL.Text,
});
export const Associate = IDL.Record({
  'id' : AssociateId,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'availability' : IDL.Text,
  'addedAt' : Timestamp,
  'skills' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Inquiry = IDL.Record({
  'id' : InquiryId,
  'status' : InquiryStatus,
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const PartnerLead = IDL.Record({
  'id' : PartnerLeadId,
  'selectedModel' : IDL.Text,
  'status' : InquiryStatus,
  'monthlyBudget' : IDL.Text,
  'submittedAt' : Timestamp,
  'corporateEmail' : IDL.Text,
  'companyName' : IDL.Text,
  'techStackNeeded' : IDL.Text,
});
export const Partner = IDL.Record({
  'id' : PartnerId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'logoUrl' : IDL.Text,
  'addedAt' : Timestamp,
  'industry' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAssociate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addPartner' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAssociate' : IDL.Func([AssociateId], [IDL.Text], []),
  'deleteAssociateApplication' : IDL.Func(
      [AssociateApplicationId],
      [IDL.Text],
      [],
    ),
  'deleteInquiry' : IDL.Func([InquiryId], [IDL.Text], []),
  'deletePartner' : IDL.Func([PartnerId], [IDL.Text], []),
  'deletePartnerLead' : IDL.Func([PartnerLeadId], [IDL.Text], []),
  'getAssociateApplications' : IDL.Func(
      [],
      [IDL.Vec(AssociateApplication)],
      ['query'],
    ),
  'getAssociates' : IDL.Func([], [IDL.Vec(Associate)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getPartnerLeads' : IDL.Func([], [IDL.Vec(PartnerLead)], ['query']),
  'getPartners' : IDL.Func([], [IDL.Vec(Partner)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAssociateApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'submitPartnerLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'updateAssociate' : IDL.Func(
      [AssociateId, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'updateAssociateApplicationStatus' : IDL.Func(
      [AssociateApplicationId, InquiryStatus],
      [IDL.Text],
      [],
    ),
  'updateInquiryStatus' : IDL.Func([InquiryId, InquiryStatus], [IDL.Text], []),
  'updatePartner' : IDL.Func(
      [PartnerId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'updatePartnerLeadStatus' : IDL.Func(
      [PartnerLeadId, InquiryStatus],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AssociateId = IDL.Nat;
  const AssociateApplicationId = IDL.Nat;
  const InquiryId = IDL.Nat;
  const PartnerId = IDL.Nat;
  const PartnerLeadId = IDL.Nat;
  const InquiryStatus = IDL.Variant({
    'new' : IDL.Null,
    'closed' : IDL.Null,
    'reviewed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const AssociateApplication = IDL.Record({
    'id' : AssociateApplicationId,
    'cvBlobKey' : IDL.Text,
    'status' : InquiryStatus,
    'yearsOfExperience' : IDL.Text,
    'fullName' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'techStackOrRole' : IDL.Text,
  });
  const Associate = IDL.Record({
    'id' : AssociateId,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'availability' : IDL.Text,
    'addedAt' : Timestamp,
    'skills' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Inquiry = IDL.Record({
    'id' : InquiryId,
    'status' : InquiryStatus,
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PartnerLead = IDL.Record({
    'id' : PartnerLeadId,
    'selectedModel' : IDL.Text,
    'status' : InquiryStatus,
    'monthlyBudget' : IDL.Text,
    'submittedAt' : Timestamp,
    'corporateEmail' : IDL.Text,
    'companyName' : IDL.Text,
    'techStackNeeded' : IDL.Text,
  });
  const Partner = IDL.Record({
    'id' : PartnerId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'logoUrl' : IDL.Text,
    'addedAt' : Timestamp,
    'industry' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAssociate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addPartner' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAssociate' : IDL.Func([AssociateId], [IDL.Text], []),
    'deleteAssociateApplication' : IDL.Func(
        [AssociateApplicationId],
        [IDL.Text],
        [],
      ),
    'deleteInquiry' : IDL.Func([InquiryId], [IDL.Text], []),
    'deletePartner' : IDL.Func([PartnerId], [IDL.Text], []),
    'deletePartnerLead' : IDL.Func([PartnerLeadId], [IDL.Text], []),
    'getAssociateApplications' : IDL.Func(
        [],
        [IDL.Vec(AssociateApplication)],
        ['query'],
      ),
    'getAssociates' : IDL.Func([], [IDL.Vec(Associate)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getPartnerLeads' : IDL.Func([], [IDL.Vec(PartnerLead)], ['query']),
    'getPartners' : IDL.Func([], [IDL.Vec(Partner)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAssociateApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'submitPartnerLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'updateAssociate' : IDL.Func(
        [
          AssociateId,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'updateAssociateApplicationStatus' : IDL.Func(
        [AssociateApplicationId, InquiryStatus],
        [IDL.Text],
        [],
      ),
    'updateInquiryStatus' : IDL.Func(
        [InquiryId, InquiryStatus],
        [IDL.Text],
        [],
      ),
    'updatePartner' : IDL.Func(
        [PartnerId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'updatePartnerLeadStatus' : IDL.Func(
        [PartnerLeadId, InquiryStatus],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };