/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Associate {
  'id' : AssociateId,
  'bio' : string,
  'name' : string,
  'role' : string,
  'availability' : string,
  'addedAt' : Timestamp,
  'skills' : Array<string>,
}
export interface AssociateApplication {
  'id' : AssociateApplicationId,
  'cvBlobKey' : string,
  'status' : InquiryStatus,
  'yearsOfExperience' : string,
  'fullName' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'techStackOrRole' : string,
}
export type AssociateApplicationId = bigint;
export type AssociateId = bigint;
export interface Inquiry {
  'id' : InquiryId,
  'status' : InquiryStatus,
  'serviceType' : string,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'company' : string,
  'message' : string,
  'phone' : string,
}
export type InquiryId = bigint;
export type InquiryStatus = { 'new' : null } |
  { 'closed' : null } |
  { 'reviewed' : null };
export interface Partner {
  'id' : PartnerId,
  'name' : string,
  'description' : string,
  'logoUrl' : string,
  'addedAt' : Timestamp,
  'industry' : string,
}
export type PartnerId = bigint;
export interface PartnerLead {
  'id' : PartnerLeadId,
  'selectedModel' : string,
  'status' : InquiryStatus,
  'monthlyBudget' : string,
  'submittedAt' : Timestamp,
  'corporateEmail' : string,
  'companyName' : string,
  'techStackNeeded' : string,
}
export type PartnerLeadId = bigint;
export type Timestamp = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAssociate' : ActorMethod<
    [string, string, Array<string>, string, string],
    string
  >,
  'addPartner' : ActorMethod<[string, string, string, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAssociate' : ActorMethod<[AssociateId], string>,
  'deleteAssociateApplication' : ActorMethod<[AssociateApplicationId], string>,
  'deleteInquiry' : ActorMethod<[InquiryId], string>,
  'deletePartner' : ActorMethod<[PartnerId], string>,
  'deletePartnerLead' : ActorMethod<[PartnerLeadId], string>,
  'getAssociateApplications' : ActorMethod<[], Array<AssociateApplication>>,
  'getAssociates' : ActorMethod<[], Array<Associate>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getPartnerLeads' : ActorMethod<[], Array<PartnerLead>>,
  'getPartners' : ActorMethod<[], Array<Partner>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAssociateApplication' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, string, string],
    string
  >,
  'submitPartnerLead' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'updateAssociate' : ActorMethod<
    [AssociateId, string, string, Array<string>, string, string],
    string
  >,
  'updateAssociateApplicationStatus' : ActorMethod<
    [AssociateApplicationId, InquiryStatus],
    string
  >,
  'updateInquiryStatus' : ActorMethod<[InquiryId, InquiryStatus], string>,
  'updatePartner' : ActorMethod<
    [PartnerId, string, string, string, string],
    string
  >,
  'updatePartnerLeadStatus' : ActorMethod<
    [PartnerLeadId, InquiryStatus],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];